export const LEVEL_WORLD_SCALE = 0.6;

export const STAGE_WIDTH = 2400 * LEVEL_WORLD_SCALE;
export const STAGE_HEIGHT = 1350 * LEVEL_WORLD_SCALE;
export const MIN_STAGE_WIDTH = 800 * LEVEL_WORLD_SCALE;
export const MAX_STAGE_WIDTH = 4000 * LEVEL_WORLD_SCALE;
export const MIN_STAGE_HEIGHT = 800 * LEVEL_WORLD_SCALE;
export const MAX_STAGE_HEIGHT = 6000 * LEVEL_WORLD_SCALE;
export const GRID_SIZE = 25 * LEVEL_WORLD_SCALE;
export const GRID_MAJOR_INTERVAL = 2;
export const STAGE_SIZE_STEP = GRID_SIZE * GRID_MAJOR_INTERVAL;
export const COURSE_STROKE_WIDTH = GRID_SIZE;
export const MIN_WALL_THICKNESS = 5 * LEVEL_WORLD_SCALE;
export const MAX_WALL_THICKNESS = 100 * LEVEL_WORLD_SCALE;
export const MAX_MARBLE_RADIUS = 8 * LEVEL_WORLD_SCALE;
export const MIN_MARBLE_RADIUS = 2 * LEVEL_WORLD_SCALE;
export const MARBLE_RADIUS_STEP = 0.25 * LEVEL_WORLD_SCALE;
export const STAGING_MARBLE_GAP = 1 * LEVEL_WORLD_SCALE;
export const STAGING_MARBLE_PADDING = 5 * LEVEL_WORLD_SCALE;
export const DEFAULT_LAUNCH_SPEED = 70 * LEVEL_WORLD_SCALE;

export const WALL_COLOR = [113 / 255, 113 / 255, 122 / 255, 1] as const;
export const BUMPER_COLOR = [168 / 255, 85 / 255, 247 / 255, 1] as const;
export const FINISH_COLOR = [239 / 255, 68 / 255, 68 / 255, 1] as const;
export const SPAWN_COLOR = [34 / 255, 211 / 255, 238 / 255, 1] as const;
